### ISSUE TITLE
Crash Report: 2.0.9.20??

### ISSUE THREAD

**Issue by IvoryMemory** [imchillin/CMTool#64]
Opened CMTools for the first time in a while and it's giving me this crash report every time I open it:

Concept Matirx ran into an error.

Please submit a bug report with the following information.
 
======================================================
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet race column hash mismatch! expected hash: 1019666222, actual hash: 872644730!
   at Lumina.Excel.ExcelModule.GetSheet[T](String name, Language language, Nullable`1 expectedHash)
   at Lumina.Excel.ExcelModule.GetSheet[T](Language language)
   at ConceptMatrix.ViewModel.MainViewModel.<>c.<Initialize>b__37_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet race column hash mismatch! expected hash: 1019666222, actual hash: 872644730!
   at Lumina.Excel.ExcelModule.GetSheet[T](String name, Language language, Nullable`1 expectedHash)
   at Lumina.Excel.ExcelModule.GetSheet[T](Language language)
   at ConceptMatrix.ViewModel.MainViewModel.<>c.<Initialize>b__37_0()
   at System.Threading.Tasks.Task.Execute()<---

======================================================
Concept Matirx ran into an error.

Please submit a bug report with the following information.
 
======================================================
System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made.
   at System.Windows.OleServicesContext.SetDispatcherThread()
   at System.Windows.OleServicesContext.get_CurrentOleServicesContext()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at ConceptMatrix.App.TaskSchedulerOnUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
======================================================

I even tried redownloading it and now I'm not sure what to do... Any ideas?

**Comment by Ingvi5959** [comment]
Just wanted to add in - I am also having this exact same issue! Came directly following the 5.4 update. Reinstall is not fixing.

**Comment by JLinari** [comment]
I'm guessing this is the offsets not having been changed for 5.4 yet, it should get fixed soon-ish probably?

**Comment by DesperateOriginal** [comment]
Same issue is happening to me. It's probably a 5.4 problem, I've tried reinstalling and it still doesn't work.

**Comment by atuican** [comment]
Yeah, I have the exact same issue on my end. Guess it's just something to be fixed next patch.

**Comment by lion-the-ryan** [comment]
Same problem D:

**Comment by Pythonsecuritypractioner** [comment]
Getting a similar error message. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at ConceptMatrix.Utility.FlexibleMessageBox.FlexibleMessageBoxForm.FlexibleMessageBoxForm_KeyUp(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyUp(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ConceptMatrix
    Assembly Version: 2.0.9.20
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MahApps.Metro
    Assembly Version: 1.6.5.1
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
MaterialDesignThemes.Wpf
    Assembly Version: 2.5.1.1345
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
MaterialDesignColors
    Assembly Version: 1.1.3.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
MaterialDesignThemes.MahApps
    Assembly Version: 0.0.10.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ControlzEx
    Assembly Version: 3.0.2.4
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
System.Windows.Interactivity
    Assembly Version: 4.5.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
Lumina
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Lumina.Generated
    Assembly Version: 1.0.0.0
    Win32 Version: 2.0.9.20
    CodeBase: file:///D:/Games/FFXIV%20Mods/ConceptMatrix.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by LD6** [comment]
god damn people

**ITS**
**NOT**
**UPDATED**

**Comment by Pythonsecuritypractioner** [comment]
> 
> 
> god damn people
> 
> **ITS**
> **NOT**
> **UPDATED**

Sounds good. Thanks for confirming.

**Comment by LD6** [comment]
> > god damn people
> > **ITS**
> > **NOT**
> > **UPDATED**
> 
> pretty sure this is the place where we post about issues, not bitch about people posting about issues

the thing is that this is not an issue. of course the mod won't work, the game just went through a massive update. 
If you bothered being on the discord or just searching it up you would see that it's not goddamn updated

**Comment by MormonJesus69420** [comment]
People, please this is not the place for fighting or arguing. The tool needs to be updated, until then please show some patience and understanding that not everyone knows about the need for update.

Closing this issue.
