### ISSUE TITLE
Issue with saving and loading in cmtool

### ISSUE THREAD

**Issue by Apoxiosis** [imchillin/CMTool#88]
Howdy, Im gonna link some screenshots and a brief summary of whats happening and hopefully you can help me figure it out.

In my concept matrix i've been changing a couple of the "world" camera settings, and been doing it manually every day. What I do is change my zoom to 30 and my field of view to .95 (not field of view 2)

I also do not check the boxes to the left of them as editing the value works as is. it looks like this 

![image](https://user-images.githubusercontent.com/43189648/129837452-0345982f-cd47-40d3-bd5d-65d42be2fc5c.png)

However, when i try to save those settings and then load them, it toggles on multiple settings (checks the boxes) and generally messes a lot of stuff up. It looks like this

![image](https://user-images.githubusercontent.com/43189648/129837571-2027a4fb-6a99-437a-bcaa-f80a73482bee.png)

i did not check any of the boxes beforehand when i saved nor did I edit any of those values, so Im lost as to why they get checked on when I load the file. I've tried clicking "save" and then "load" as well as clicking the floppy disc icon to save it as a file and load it from said file, both results on all of these settings getting toggled on and generally takes more time to turn them off than it takes to manually edit my zoom and fov.

Do you have any thoughts?

**Comment by DAOWAce** [comment]
I suppose that means it won't be changed..

Been having to do this myself for **actual years** as even manually editing the file it saves doesn't seem to work.

Asking about any of this 'world' stuff over in the newer Anamnesis tool gets your issue instantly closed because they think it's "cheating" (in a PvE game?) and lock it to GPose. Meanwhile most people I know using CMTool do so because it makes playing the game more comfortable (especially zoom levels which some other MMOs have options to go further, and FoV as 78 is a bit narrow).

Having to set the options every single time we start the client is quite a frustration that seems like it has an easy solution to resolve.  I'd have probably tried to do it myself if I knew how to code..

**Comment by LeonBlade** [comment]
Just use [Cammy](https://github.com/UnknownX7/Cammy) if you care about camera stuff. It has features for all of that stuff.
